name: Build and test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
        channel: "stable"

    - name: Setup project
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Create env file
      run: |
        touch .env
        echo "GRAPH_API_CLIENT_ID=${{ secrets.GRAPH_API_CLIENT_ID }}" > .env

    # - name: Build for Android
    #   run: flutter build apk

    - name: Test
      run: flutter test

  build-for-ios:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.1'
        channel: "stable"

    - name: Setup project
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Create env file
      run: |
        touch .env
        echo "GRAPH_API_CLIENT_ID=${{ secrets.GRAPH_API_CLIENT_ID }}" > .env

    - name: Build for iOS
      env:
        API_KEY_ID: ${{ secrets.API_KEY_ID }}
        API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
        API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
        DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        cd ios
        bundle exec fastlane build_and_deploy skip_deploy:true
