name: Deploy iOS

on: push

jobs:
  deploy-ios:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.5'
        channel: "stable"

    - name: Setup project
      run: |
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Deploy
      env:
        API_KEY_ID: ${{ secrets.API_KEY_ID }}
        API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
        API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
      run: |
        cd ios
        bundle exec fastlane release

    - name: Clean up keychain and provisioning profile
      if: ${{ always() }}
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
        rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision